const agu = {
    name: 'Aguascalientes',
    cities: [
        "Aguascalientes",
        "Asientos",
        "Calvillo",
        "Cosío",
        "El Llano",
        "Jesús María",
        "Pabellón de Arteaga",
        "Rincón de Romos",
        "San Francisco de los Romo",
        "San José de Gracia",
        "Tepezalá"
    ]
}

const bcn = {
    name: 'Baja California',
    cities: [
        "Mexicali",
        "Ensenada",
        "Playas de Rosarito",
        "San Quintín",
        "Tecate",
        "Tijuana"
    ]
}

const bcs = {
    name: 'Baja California Sur',
    cities: [
        "La Paz",
        "Comondú",
        "Loreto",
        "Los Cabos",
        "Mulegé"
    ]
}

const cam = {
    name: 'Campeche',
    cities: [
        "Campeche",
        "Calakmul",
        "Calkiní",
        "Candelaria",
        "Carmen",
        "Champotón",
        "Dzitbalché",
        "Escárcega",
        "Hecelchakán",
        "Hopelchén",
        "Palizada",
        "Seybaplaya",
        "Tenabo"
    ]
}

const cdm = {
    name: 'Ciudad de México',
    cities: [
        'Álvaro Obregón',
        'Azcapotzalco',
        'Benito Juárez',
        'Coyoacán',
        'Cuajimalpa',
        'Cuauhtémoc',
        'Gustavo A. Madero',
        'Iztacalco',
        'Iztapalapa',
        'Magdalena Contreras',
        'Miguel Hidalgo',
        'Milpa Alta',
        'Tláhuac',
        'Tlalpan',
        'Venustiano Carranza',
        'Xochimilco'
    ]
}

const chh = {
    name: 'Chihuahua',
    cities: [
        "Ahumada",
        "Aldama",
        "Allende",
        "Aquiles Serdán",
        "Ascensión",
        "Bachíniva",
        "Balleza",
        "Batopilas",
        "Bocoyna",
        "Buenaventura",
        "Camargo",
        "Carichí",
        "Casas Grandes",
        "Chihuahua",
        "Chínipas",
        "Ciudad Juárez",
        "Coronado",
        "Coyame",
        "Cuauhtémoc",
        "Cusihuiriachi",
        "Delicias",
        "Dr. Belisario Domínguez",
        "El Tule",
        "Galeana",
        "Gómez Farías",
        "Gran Morelos",
        "Guachochi",
        "Guadalupe",
        "Guadalupe y Calvo",
        "Guazapares",
        "Guerrero",
        "Hidalgo del Parral",
        "Huejotitán",
        "Ignacio Zaragoza",
        "Janos",
        "Jiménez",
        "Julimes",
        "La Cruz",
        "López",
        "Madera",
        "Maguarichi",
        "Manuel Benavides",
        "Matachí",
        "Matamoros",
        "Meoqui",
        "Morelos",
        "Moris",
        "Namiquipa",
        "Nonoava",
        "Nuevo Casas Grandes",
        "Ocampo",
        "Ojinaga",
        "Praxedis G. Guerrero",
        "Riva Palacio",
        "Rosales",
        "Rosario",
        "San Francisco de Borja",
        "San Francisco de Conchos",
        "San Francisco del Oro",
        "Santa Bárbara",
        "Santa Isabel",
        "Satevó",
        "Saucillo",
        "Temósachi",
        "Urique",
        "Uruachi",
        "Valle de Zaragoza"
    ]
}

const chp = {
    name: 'Chiapas',
    cities: [
        "Acacoyagua",
        "Acala",
        "Acapetahua",
        "Aldama",
        "Altamirano",
        "Amatán",
        "Amatenango de la Frontera",
        "Amatenango del Valle",
        "Ángel Albino Corzo",
        "Arriaga",
        "Bejucal de Ocampo",
        "Belisario Domínguez",
        "Bella Vista",
        "Benemérito de las Américas",
        "Berriozábal",
        "Bochil",
        "Cacahoatán",
        "Capitán Luis Ángel Vidal",
        "Catazajá",
        "Chalchihuitán",
        "Chamula",
        "Chanal",
        "Chapultenango",
        "Chenalhó",
        "Chiapa de Corzo",
        "Chiapilla",
        "Chicoasén",
        "Chicomuselo",
        "Chilón",
        "Cintalapa",
        "Coapilla",
        "Comitán de Domínguez",
        "Copainalá",
        "El Bosque",
        "El Parral",
        "El Porvenir",
        "Emiliano Zapata",
        "Escuintla",
        "Francisco León",
        "Frontera Comalapa",
        "Frontera Hidalgo",
        "Huehuetán",
        "Huitiupán",
        "Huixtán",
        "Huixtla",
        "Ixhuatán",
        "Ixtacomitán",
        "Ixtapa",
        "Ixtapangajoya",
        "Jiquipilas",
        "Jitotol",
        "Juárez",
        "La Concordia",
        "La Grandeza",
        "La Independencia",
        "La Libertad",
        "La Trinitaria",
        "Larráinzar",
        "Las Margaritas",
        "Las Rosas",
        "Mapastepec",
        "Maravilla Tenejapa",
        "Marqués de Comillas",
        "Mazapa de Madero",
        "Mazatán",
        "Metapa",
        "Mezcalapa",
        "Mitontic",
        "Montecristo de Guerrero",
        "Motozintla",
        "Nicolás Ruiz",
        "Ocosingo",
        "Ocotepec",
        "Ocozocoautla de Espinosa",
        "Ostuacán",
        "Osumacinta",
        "Oxchuc",
        "Palenque",
        "Pantelhó",
        "Pantepec",
        "Pichucalco",
        "Pijijiapan",
        "Pueblo Nuevo Solistahuacán",
        "Rayón",
        "Reforma",
        "Rincón Chamula San Pedro",
        "Sabanilla",
        "Salto de Agua",
        "San Andrés Duraznal",
        "San Cristóbal de las Casas",
        "San Fernando",
        "San Juan Cancuc",
        "San Lucas",
        "Santiago el Pinar",
        "Siltepec",
        "Simojovel",
        "Sitalá",
        "Socoltenango",
        "Solosuchiapa",
        "Soyaló",
        "Suchiapa",
        "Suchiate",
        "Sunuapa",
        "Tapachula",
        "Tapalapa",
        "Tapilula",
        "Tecpatán",
        "Tenejapa",
        "Teopisca",
        "Tila",
        "Tonalá",
        "Totolapa",
        "Tumbalá",
        "Tuxtla Chico",
        "Tuxtla Gutiérrez",
        "Tuzantán",
        "Tzimol",
        "Unión Juárez",
        "Venustiano Carranza",
        "Villa Comaltitlán",
        "Villa Corzo",
        "Villaflores",
        "Yajalón",
        "Zinacantán"
    ]
}

const coa = {
    name: 'Coahuila',
    cities: [
        "Abasolo",
        "Acuña",
        "Allende",
        "Arteaga",
        "Candela",
        "Castaños",
        "Saltillo",
        "Cuatro Ciénegas",
        "Escobedo",
        "Francisco I. Madero",
        "Frontera",
        "General Cepeda",
        "Guerrero",
        "Hidalgo",
        "Jiménez",
        "Juárez",
        "Lamadrid",
        "Matamoros",
        "Monclova",
        "Morelos",
        "Múzquiz",
        "Nadadores",
        "Nava",
        "Ocampo",
        "Parras",
        "Piedras Negras",
        "Progreso",
        "Ramos Arizpe",
        "Sabinas",
        "Sacramento",
        "San Buenaventura",
        "San Juan de Sabinas",
        "San Pedro",
        "Sierra Mojada",
        "Torreón",
        "Viesca",
        "Villa Unión",
        "Zaragoza"
    ]
}

const col = {
    name: 'Colima',
    cities: [
        "Armería",
        "Colima",
        "Comala",
        "Coquimatlán",
        "Cuauhtémoc",
        "Ixtlahuacán",
        "Manzanillo",
        "Minatitlán",
        "Tecomán",
        "Villa de Álvarez"
    ]
}

const dur = {
    name: 'Durango',
    cities: [
        "Canatlán",
        "Canelas",
        "Coneto de Comonfort",
        "Cuencamé",
        "Durango",
        "El Oro",
        "General Simón Bolívar",
        "Gómez Palacio",
        "Guadalupe Victoria",
        "Guanaceví",
        "Hidalgo",
        "Indé",
        "Lerdo",
        "Mapimí",
        "Mezquital",
        "Nazas",
        "Nombre de Dios",
        "Nuevo Ideal",
        "Ocampo",
        "Otáez",
        "Pánuco de Coronado",
        "Peñón Blanco",
        "Poanas",
        "Pueblo Nuevo",
        "Rodeo",
        "San Bernardo",
        "San Dimas",
        "San Juan de Guadalupe",
        "San Juan del Río",
        "San Luis del Cordero",
        "San Pedro del Gallo",
        "Santa Clara",
        "Santiago Papasquiaro",
        "Súchil",
        "Tamazula",
        "Tepehuanes",
        "Tlahualilo",
        "Topia",
        "Vicente Guerrero"
    ]
}

const gua = {
    name: 'Guanajuato',
    cities: [
        "Guanajuato",
        "Abasolo",
        "Acámbaro",
        "Apaseo El Alto",
        "Apaseo El Grande",
        "Atarjea",
        "Celaya",
        "Comonfort",
        "Coroneo",
        "Cortazar",
        "Cuerámaro",
        "Dolores Hidalgo",
        "Huanímaro",
        "Irapuato",
        "Jaral del Progreso",
        "Jerécuaro",
        "Juventino Rosas",
        "León",
        "Manuel Doblado",
        "Moroleón",
        "Ocampo",
        "Pénjamo",
        "Pueblo Nuevo",
        "Purísima del Rincón",
        "Romita",
        "Salamanca",
        "Salvatierra",
        "Santa Catarina",
        "San Diego de la Unión",
        "San Felipe",
        "San Francisco del Rincón",
        "San José Iturbide",
        "San Luis de la Paz",
        "San Miguel de Allende",
        "Santiago Maravatío",
        "Silao",
        "Tarandacuao",
        "Tarimoro",
        "Tierra Blanca",
        "Uriangato",
        "Valle de Santiago",
        "Victoria",
        "Villa Doctor Mora",
        "Villagrán",
        "Xichú",
        "Yuriria"
    ]
}

const jal = {
    name: 'Jalisco',
    cities:[
        "Acatic",
        "Acatlán de Juárez",
        "Ahualulco de Mercado",
        "Amacueca",
        "Amatitán",
        "Ameca",
        "Arandas",
        "Atemajac de Brizuela",
        "Atengo",
        "Atenguillo",
        "Atotonilco el Alto",
        "Atoyac",
        "Autlán de Navarro",
        "Ayotlán",
        "Ayutla",
        "Bolaños",
        "Cabo Corrientes",
        "Cañadas de Obregón",
        "Casimiro Castillo",
        "Chapala",
        "Chimaltitán",
        "Chiquilistlán",
        "Cihuatlán",
        "Cocula",
        "Colotlán",
        "Concepción de Buenos Aires",
        "Cuautitlán de García Barragán",
        "Cuautla",
        "Cuquío",
        "Degollado",
        "Ejutla",
        "El Arenal",
        "El Grullo",
        "El Limón",
        "El Salto",
        "Encarnación de Díaz",
        "Etzatlán",
        "Gómez Farías",
        "Guachinango",
        "Guadalajara",
        "Hostotipaquillo",
        "Huejúcar",
        "Huejuquilla el Alto",
        "Ixtlahuacán de los Membrillos",
        "Ixtlahuacán del Río",
        "Jalostotitlán",
        "Jamay",
        "Jesús María",
        "Jilotlán de los Dolores",
        "Jocotepec",
        "Juanacatlán",
        "Juchitlán",
        "La Barca",
        "La Huerta",
        "La Manzanilla de la Paz",
        "Lagos de Moreno",
        "Magdalena",
        "Mascota",
        "Mazamitla",
        "Mexticacán",
        "Mezquitic",
        "Mixtlán",
        "Ocotlán",
        "Ojuelos de Jalisco",
        "Pihuamo",
        "Poncitlán",
        "Puerto Vallarta",
        "Quitupan",
        "San Cristóbal de la Barranca",
        "San Diego de Alejandría",
        "San Gabriel",
        "San Ignacio Cerro Gordo",
        "San Juan de los Lagos",
        "San Juanito de Escobedo",
        "San Julián",
        "San Marcos",
        "San Martín de Bolaños",
        "San Martín de Hidalgo",
        "San Miguel el Alto",
        "San Sebastián del Oeste",
        "Santa María de los Ángeles",
        "Santa María del Oro",
        "Sayula",
        "Tala",
        "Talpa de Allende",
        "Tamazula de Gordiano",
        "Tapalpa",
        "Tecalitlán",
        "Tecolotlán",
        "Techaluta de Montenegro",
        "Tenamaxtlán",
        "Teocaltiche",
        "Teocuitatlán de Corona",
        "Tepatitlán de Morelos",
        "Tequila",
        "Teuchitlán",
        "Tizapán el Alto",
        "Tlajomulco de Zúñiga",
        "Tlaquepaque",
        "Tolimán",
        "Tomatlán",
        "Tonalá",
        "Tonaya",
        "Tonila",
        "Totatiche",
        "Tototlán",
        "Tuxcacuesco",
        "Tuxcueca",
        "Tuxpan",
        "Unión de San Antonio",
        "Unión de Tula",
        "Valle de Guadalupe",
        "Valle de Juárez",
        "Villa Purificación",
        "Villa Corona",
        "Villa Guerrero",
        "Villa Hidalgo",
        "Yahualica de González Gallo",
        "Zacoalco de Torres",
        "Zapopan",
        "Zapotiltic",
        "Zapotitlán de Vadillo",
        "Zapotlán del Rey",
        "Zapotlán El Grande",
        "Zapotlanejo"
    ]
}

const mex = {
    name: 'Estado de México',
    cities: [
        'Acambay',
        'Acolman',
        'Aculco',
        'Almoloya de Alquisiras',
        'Almoloya de Juárez',
        'Almoloya del Río',
        'Amanalco',
        'Amatepec',
        'Amecameca',
        'Apaxco',
        'Atenco',
        'Atizapán',
        'Atizapán de Zaragoza',
        'Atlacomulco',
        'Atlautla',
        'Axapusco',
        'Ayapango',
        'Calimaya',
        'Capulhuac',
        'Chalco',
        'Chapa de Mota',
        'Chapultepec',
        'Chiautla',
        'Chicoloapan',
        'Chiconcuac',
        'Chimalhuacán',
        'Coacalco de Berriozábal',
        'Coatepec Harinas',
        'Cocotitlán',
        'Coyotepec',
        'Cuautitlán',
        'Cuautitlán Izcalli',
        'Donato Guerra',
        'Ecatepec de Morelos',
        'Ecatzingo',
        'El Oro',
        'Huehuetoca',
        'Hueypoxtla',
        'Huixquilucan',
        'Isidro Fabela',
        'Ixtapaluca',
        'Ixtapan de la Sal',
        'Ixtapan del Oro',
        'Ixtlahuaca',
        'Jaltenco',
        'Jilotepec',
        'Jilotzingo',
        'Jiquipilco',
        'Jocotitlán',
        'Joquicingo',
        'Juchitepec',
        'La Paz',
        'Lerma',
        'Luvianos',
        'Malinalco',
        'Melchor Ocampo',
        'Metepec',
        'Mexicaltzingo',
        'Morelos',
        'Naucalpan',
        'Nextlalpan',
        'Nezahualcóyotl',
        'Nicolás Romero',
        'Nopaltepec',
        'Ocoyoacac',
        'Ocuilan',
        'Otumba',
        'Otzoloapan',
        'Otzolotepec',
        'Ozumba',
        'Papalotla',
        'Polotitlán',
        'Rayón',
        'San Antonio la Isla',
        'San Felipe del Progreso',
        'San José del Rincón',
        'San Martín de las Pirámides',
        'San Mateo Atenco',
        'San Simón de Guerrero',
        'Santo Tomás',
        'Soyaniquilpan de Juárez',
        'Sultepec',
        'Tecámac',
        'Tejupilco',
        'Temamatla',
        'Temascalapa',
        'Temascalcingo',
        'Temascaltepec',
        'Temoaya',
        'Tenancingo',
        'Tenango del Aire',
        'Tenango del Valle',
        'Teoloyucan',
        'Teotihuacán',
        'Tepetlaoxtoc',
        'Tepetlixpa',
        'Tepotzotlán',
        'Tequixquiac',
        'Texcaltitlán',
        'Texcalyacac',
        'Texcoco',
        'Tezoyuca',
        'Tianguistenco',
        'Timilpan',
        'Tlalmanalco',
        'Tlalnepantla de Baz',
        'Tlatlaya',
        'Toluca',
        'Tonanitla',
        'Tonatico',
        'Tultepec',
        'Tultitlán',
        'Valle de Bravo',
        'Valle de Chalco Solidaridad',
        'Villa de Allende',
        'Villa del Carbón',
        'Villa Guerrero',
        'Villa Victoria',
        'Xalatlaco',
        'Xonacatlán',
        'Zacazonapan',
        'Zacualpan',
        'Zinacantepec',
        'Zumpahuacán',
        'Zumpango'
    ]
}

const pue = {
    name: 'Puebla',
    cities:[
        "Acajete",
        "Acateno",
        "Acatlán",
        "Acatzingo",
        "Acteopan",
        "Ahuacatlán",
        "Ahuatlán",
        "Ahuazotepec",
        "Ahuehuetitla",
        "Ajalpan",
        "Albino Zertuche",
        "Aljojuca",
        "Altepexi",
        "Amixtlán",
        "Amozoc",
        "Aquixtla",
        "Atempan",
        "Atexcal",
        "Atlequizayan",
        "Atlixco",
        "Atoyatempan",
        "Atzala",
        "Atzitzihuacán",
        "Atzitzintla",
        "Axutla",
        "Ayotoxco de Guerrero",
        "Calpan",
        "Caltepec",
        "Camocuautla",
        "Cañada Morelos",
        "Caxhuacan",
        "Chalchicomula de Sesma",
        "Chapulco",
        "Chiautla",
        "Chiautzingo",
        "Chichiquila",
        "Chiconcuautla",
        "Chietla",
        "Chigmecatitlán",
        "Chignahuapan",
        "Chignautla",
        "Chila",
        "Chila de la Sal",
        "Chilchotla",
        "Chinantla",
        "Coatepec",
        "Coatzingo",
        "Cohetzala",
        "Cohuecan",
        "Coronango",
        "Coxcatlán",
        "Coyomeapan",
        "Coyotepec",
        "Cuapiaxtla de Madero",
        "Cuautempan",
        "Cuautinchán",
        "Cuautlancingo",
        "Cuayuca de Andrade",
        "Cuetzalan del Progreso",
        "Cuyoaco",
        "Domingo Arenas",
        "Eloxochitlán",
        "Epatlán",
        "Esperanza",
        "Francisco Z. Mena",
        "General Felipe Ángeles",
        "Guadalupe",
        "Guadalupe Victoria",
        "Hermenegildo Galeana",
        "Honey",
        "Huaquechula",
        "Huatlatlauca",
        "Huauchinango",
        "Huehuetla",
        "Huehuetlán el Chico",
        "Huehuetlán el Grande",
        "Huejotzingo",
        "Hueyapan",
        "Hueytamalco",
        "Hueytlalpan",
        "Huitzilan de Serdán",
        "Huitziltepec",
        "Ixcamilpa de Guerrero",
        "Ixcaquixtla",
        "Ixtacamaxtitlán",
        "Ixtepec",
        "Izúcar de Matamoros",
        "Jalpan",
        "Jolalpan",
        "Jonotla",
        "Jopala",
        "Juan C. Bonilla",
        "Juan Galindo",
        "Juan N. Méndez",
        "La Magdalena Tlatlauquitepec",
        "Lafragua",
        "Libres",
        "Los Reyes de Juárez",
        "Mazapiltepec de Juárez",
        "Mixtla",
        "Molcaxac",
        "Naupan",
        "Nauzontla",
        "Nealtican",
        "Nicolás Bravo",
        "Nopalucan",
        "Ocotepec",
        "Ocoyucan",
        "Olintla",
        "Oriental",
        "Pahuatlán",
        "Palmar de Bravo",
        "Pantepec",
        "Petlalcingo",
        "Piaxtla",
        "Puebla de Zaragoza",
        "Quecholac",
        "Quimixtlán",
        "Rafael Lara Grajales",
        "San Andrés Cholula",
        "San Antonio Cañada",
        "San Diego La Mesa Tochimiltzingo",
        "San Felipe Teotlalcingo",
        "San Felipe Tepatlán",
        "San Gabriel Chilac",
        "San Gregorio Atzompa",
        "San José Chiapa",
        "San José Miahuatlán",
        "San Jerónimo Tecuanipan",
        "San Jerónimo Xayacatlán",
        "San Juan Atenco",
        "San Juan Atzompa",
        "San Martín Texmelucan",
        "San Martín Totoltepec",
        "San Matías Tlalancaleca",
        "San Miguel Ixitlán",
        "San Miguel Xoxtla",
        "San Nicolás Buenos Aires",
        "San Nicolás de los Ranchos",
        "San Pablo Anicano",
        "San Pedro Cholula",
        "San Pedro Yeloixtlahuaca",
        "San Salvador el Seco",
        "San Salvador el Verde",
        "San Salvador Huixcolotla",
        "San Sebastián Tlacotepec",
        "Santa Catarina Tlaltempan",
        "Santa Inés Ahuatempan",
        "Santa Isabel Cholula",
        "Santiago Miahuatlán",
        "Santo Tomás Hueyotlipan",
        "Soltepec",
        "Tecali de Herrera",
        "Tecamachalco",
        "Tecomatlán",
        "Tehuacán",
        "Tehuitzingo",
        "Tenampulco",
        "Teopantlán",
        "Teotlalco",
        "Tepanco de López",
        "Tepango de Rodríguez",
        "Tepatlaxco de Hidalgo",
        "Tepeaca",
        "Tepemaxalco",
        "Tepeojuma",
        "Tepetzintla",
        "Tepexco",
        "Tepexi de Rodríguez",
        "Tepeyahualco",
        "Tepeyahualco de Cuauhtémoc",
        "Tetela de Ocampo",
        "Teteles de Ávila Castillo",
        "Teziutlán",
        "Tianguismanalco",
        "Tilapa",
        "Tlachichuca",
        "Tlacotepec de Benito Juárez",
        "Tlacuilotepec",
        "Tlahuapan",
        "Tlaltenango",
        "Tlanepantla",
        "Tlaola",
        "Tlapacoya",
        "Tlapanalá",
        "Tlatlauquitepec",
        "Tlaxco",
        "Tochimilco",
        "Tochtepec",
        "Totoltepec de Guerrero",
        "Tulcingo",
        "Tuzamapan de Galeana",
        "Tzicatlacoyan",
        "Venustiano Carranza",
        "Vicente Guerrero",
        "Xayacatlán de Bravo",
        "Xicotepec",
        "Xicotlán",
        "Xiutetelco",
        "Xochiapulco",
        "Xochiltepec",
        "Xochitlán de Vicente Suárez",
        "Xochitlán Todos Santos",
        "Yaonáhuac",
        "Yehualtepec",
        "Zacapala",
        "Zacapoaxtla",
        "Zacatlán",
        "Zapotitlán",
        "Zapotitlán de Méndez",
        "Zaragoza",
        "Zautla",
        "Zihuateutla",
        "Zinacatepec",
        "Zongozotla",
        "Zoquiapan",
        "Zoquitlán"
    ]
}

const gro = {
    name: 'Guerrero',
    cities: [
        "Chilpancingo de los Bravo",
        "Acapulco de Juárez",
        "Acatepec",
        "Ahuacuotzingo",
        "Ajuchitlán del Progreso",
        "Alcozauca de Guerrero",
        "Alpoyeca",
        "Apaxtla de Castrejón",
        "Arcelia",
        "Atenango del Río",
        "Atlamajalcingo del Monte",
        "Atlixtac",
        "Atoyac de Álvarez",
        "Ayutla",
        "Azoyú",
        "Benito Juárez",
        "Buenavista de Cuéllar",
        "Chilapa de Álvarez",
        "Coahuayutla de José María Izazaga",
        "Cochoapa el Grande",
        "Cocula",
        "Copala",
        "Copalillo",
        "Copanatoyac",
        "Coyuca de Benítez",
        "Coyuca de Catalán",
        "Cuajinicuilapa",
        "Cualác",
        "Cuautepec",
        "Cuetzala del Progreso",
        "Cutzamala de Pinzón",
        "Eduardo Neri",
        "Florencio Villarreal",
        "General Canuto A. Neri",
        "General Heliodoro Castillo",
        "Huamuxtitlán",
        "Huitzuco de los Figueroa",
        "Iguala de la Independencia",
        "Igualapa",
        "Iliatenco",
        "Ixcateopan de Cuauhtémoc",
        "José Joaquín de Herrera",
        "Juan R. Escudero",
        "Juchitán",
        "La Unión de Isidoro Montes de Oca",
        "Leonardo Bravo",
        "Malinaltepec",
        "Marquelia",
        "Mártir de Cuilapan",
        "Metlatónoc",
        "Mochitlán",
        "Olinalá",
        "Ometepec",
        "Pedro Ascencio Alquisiras",
        "Petatlán",
        "Pilcaya",
        "Pungarabato",
        "Quechultenango",
        "San Luis Acatlán",
        "San Marcos",
        "San Miguel Totolapan",
        "Taxco de Alarcón",
        "Tecoanapa",
        "Tecpan de Galeana",
        "Teloloapan",
        "Tepecoacuilco de Trujano",
        "Tetipac",
        "Tixtla de Guerrero",
        "Tlacoachistlahuaca",
        "Tlacoapa",
        "Tlalchapa",
        "Tlalixtaquilla de Maldonado",
        "Tlapa de Comonfort",
        "Tlapehuala",
        "Xalpatláhuac",
        "Xochihuehuetlán",
        "Xochistlahuaca",
        "Zapotitlán Tablas",
        "Zihuatanejo de Azueta",
        "Zirándaro",
        "Zitlala"
    ]
}

const mxn = {
    name: 'México',
    states: {
        agu,
        bcn,
        bcs,
        cam,
        chh,
        chp,
        coa,
        col,
        cdm,
        dur,
        jal,
        mex,
        pue,
        gua,
        gro
    }
}


module.exports = mxn